### ISSUE TITLE
pom.xml   and  .gitignore

### ISSUE THREAD

**Issue by asdtiang** [why2012/jNetty#1]
好，我是 arvix 的，简单看了下代码，很明显的两个问题，希望改进，会持续关注你的项目。
pom.xml文件里不应该有Alpha2，http://mvnrepository.com/artifact/javax.servlet/javax.servlet-api   servlet3.1早就有正式版本放出。

.setting  , target目录等不应该放到git里做源码管理。

**Comment by why2012** [comment]
感谢你的宝贵意见，会持续改进的！

**Comment by why2012** [comment]
对了，有没有什么程序设计方面的bug或不合理的地方呢？目前还没有加Jasper来解析jsp，以后会加上
